---
- name: default FTS-UI config file
  ansible.builtin.copy:
    src: config.py
    dest: "{{ fts_ui_install_path }}/config.py"
    owner: fts
    group: fts
    mode: 0664
  notify: "Activate fts_ui Service"

- name: Template config file
  ansible.builtin.template:
    src: FTS_UIConfig.yaml.j2
    dest: "/opt/fts/FTS_UIConfig.yaml"
    owner: fts
    group: fts
    mode: 0664
  notify: "Activate fts_ui Service"

- name: Template unit file
  become: true
  become_user: root
  ansible.builtin.template:
    src: fts-ui.service.j2
    dest: "{{ unit_files_location }}/{{ fts_ui_service_name }}.service"
    owner: root
    group: root
    mode: 0664
  notify: "Activate fts_ui Service"

#- name: Kill any currently running processes
#  include_tasks: ../../common/tasks/kill.yml
#  vars:
#    process: "{{ fts_ui_install_path }}/run.py"

- name: "Enable fts_ui service"
  ansible.builtin.systemd_service:
    name: "{{ fts_ui_service_name }}"
    enabled: "{{ fts_ui_enabled }}"
    daemon_reload: true
  notify: "Activate fts_ui Service"

...
