---
- name: Delete PyYAML
  shell: "{{ item }}"
  loop:
    - "rm -rf {{ fts_venv }}/lib/python3.11/site-packages/yaml"
    - "rm -rf {{ fts_venv }}/lib/python3.11/site-packages/PyYAML-*"

- name: Install apt packages
  apt:
    name: "{{ fts_ui_apt_packages }}"

- name: "Install pip FTS UI packages"
  ansible.builtin.pip:
    name: "{{ fts_ui_pip_packages }}"
    virtualenv: "{{ fts_venv }}"
  environment:
    PIP_EXTRA_INDEX_URL: "{{ pypi_url }}"

- name: "Install pip FTS UI packages"
  ansible.builtin.pip:
    name: "{{ fts_ui_pip_package_name }}"
    virtualenv: "{{ fts_venv }}"
  environment:
    PIP_EXTRA_INDEX_URL: "{{ pypi_url }}"

- name: "Change owner of {{ fts_venv }} to fts"
  ansible.builtin.file:
    path: "{{ fts_venv }}"
    owner: "fts"
    group: "fts"
    recurse: true
    state: "directory"
...
