---
- name: Install Node-RED Server
  hosts: all
  vars:
    # Node-RED Server will wait for Video Server
    nodered_wait_for_videoserver: false
    # Max seconds Node-RED Server will wait
    nodered_wait_for_videoserver_timeout: 600
  become: true
  become_user: root
  pre_tasks:
    - name: Cleanup
      import_tasks: roles/common/tasks/cleanup.yml

  post_tasks:
    - name: Reload Node-RED Server flows to ensure Video Server connection
      import_tasks: roles/nodered/tasks/reload-flows.yml

    - name: Cleanup
      import_tasks: roles/common/tasks/cleanup.yml

  roles:
    - nodered
...
