---
- name: "Skipping webmap install due to non-intel platform"
  debug:
    msg: "non-intel, skipping webmap install"
  when: (ansible_architecture != "x86_64") or (not webmap_force_install)

- name: Get public IPv4
  uri:
    url: http://ifconfig.me/ip
    return_content: true
  register: ip_response

- name: Set public IPv4
  set_fact:
    webmap_public_ipv4: "{{ ip_response.content }}"
  when: fts_ip_addr_extra is undefined

- name: Set public IPv4
  set_fact:
    webmap_public_ipv4: "{{ fts_ip_addr_extra }}"
  when: fts_ip_addr_extra is defined

- name: Print IPv4
  debug:
    msg: "webmap_public_ipv4 = {{ webmap_public_ipv4 }}"

- name: Set localhost IPv4
  set_fact:
    webmap_ipv4: 127.0.0.1

  # ansible_archtecture mappings:
  # x86_64: amd64
  # ppc64le: ppc64el
  # s390x: s390x
  # armv7l: armhf
  # aarch64: arm64

- name: "Include {{ ansible_distribution }}-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"
  when: (ansible_architecture == "x86_64") or (webmap_force_install)

- name: Setup
  include_tasks: "setup-{{ ansible_distribution }}.yml"
  when: (ansible_architecture == "x86_64") or (webmap_force_install)

- name: "Configure webmap for {{ ansible_distribution }}"
  include_tasks: "configure-{{ ansible_distribution }}.yml"
  when: (ansible_architecture == "x86_64") or (webmap_force_install)
...
