---

- name: "Activate fts_ui Service"
  ansible.builtin.systemd_service:
    name: "{{ fts_ui_service_name }}"
    state: "restarted"
  listen: "Activate fts_ui Service"
  register: activate_fts_ui_status
  retries: 5
  ignore_errors: true
  until: activate_fts_ui_status is succeeded

- name: print fts_ui url
  debug:
    msg: "FreeTAKServer-UI URL: https://{{ fts_ui_ipv4 }}:5000/"

- name: print fts_ui credentials
  debug:
    msg: "username: admin     password: password"
...
