---
- name: enable videoserver
  service:
    name: "{{ videoserver_service_name }}"
    enabled: "{{ videoserver_enabled }}"

- name: reload videoserver
  service:
    name: "{{ videoserver_service_name }}"
    state: reloaded

- name: set videoserver state
  service:
    name: "{{ videoserver_service_name }}"
    state: "{{ videoserver_state }}"

- name: print videoserver url
  debug:
    msg: "Video Server URL: http://{{ videoserver_ipv4 }}:9997/v1/config/get"
...
