---

- name: Install apt dependencies
  apt:
    name: "{{ fts_apt_dependencies | list }}"

#- name: "Install {{ fts_pip_package_name }} from github repo"
#  shell: "{{ item }}"
#  loop:
#    - "git clone https://github.com/FreeTAKTeam/FreeTakServer.git /FreeTakServer"
#    - "git -C /FreeTakServer reset --hard 109b674"
#    - "pip install /FreeTakServer"

- name: "Install {{ fts_pip_package_name }}"
  become: true
  become_user: root
  ansible.builtin.pip:
#    name: "{{ fts_pip_package_name }}=={{ fts_version }}"
    name: 'git+https://github.com/FreeTAKTeam/FreeTakServer.git@705-unable-to-install-broken-dependencies'
    virtualenv: "{{ fts_venv }}"
    state: "present"
  environment:
    PIP_EXTRA_INDEX_URL: "{{ pypi_url }}"

- name: "Change owner of {{ fts_venv }} to fts"
  ansible.builtin.file:
    path: "{{ fts_venv }}"
    owner: "fts"
    group: "fts"
    recurse: true
    state: "directory"
...
