---
webmap_force_install: false

webmap_ipv4: 0.0.0.0

webmap_api_url: https://api.github.com/repos/FreeTAKTeam/FreeTAKHub/releases/latest
webmap_package: webmap.zip
webmap_executable: FTH-webmap-linux
webmap_raw_executable_name: FTH-webmap-linux-0.2.5
webmap_config_file: webMAP_config.json

webmap_service_name: webmap

# Set initial service state. Recommended values: `started` or `stopped`.
webmap_state: started

# Enable service.
webmap_enabled: true
...
