---
- name: DIFFERENT SERVICES ON DIFFERENT HOSTS
  hosts: all
  become: true
  vars:

    # Node-RED Server will wait for Video Server
    nodered_wait_for_videoserver: true

    # Max seconds Node-RED Server will wait
    nodered_wait_for_videoserver_timeout: 600

  pre_tasks:

    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

    - name: Include IPv4 address variables
      include_vars: ../../ip_addresses.yml

  post_tasks:

    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

- hosts: freetakserver
  roles:
    - freetakserver
    - freetakserver_ui
    - webmap

- hosts: videoserver
  roles:
    - videoserver

- hosts: murmur
  roles:
    - murmur

- hosts: noderedserver
  roles:
    - nodered
...
