---
- name: activate freetakserver service
  ansible.builtin.systemd_service:
    name: "{{ fts_service_name }}"
    enabled: "{{ fts_enabled }}"
    state: "{{ fts_state }}"
    daemon_reload: true
...
