---
- name: Install All On One Docker Image
  hosts: instance
  become: true

  pre_tasks:

    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

    - name: Include IPv4 address variables
      include_vars: ../../ip_addresses.yml

  post_tasks:

    - name: Cleanup
      import_tasks: ../../roles/common/tasks/cleanup.yml

  roles:
    - role: freetakserver
      ignore_errors: yes
    - role: freetakserver_ui
      ignore_errors: yes
    - role: webmap
      ignore_errors: yes
    - role: murmur
      ignore_errors: yes
    - role: videoserver
      ignore_errors: yes
    - role: nodered
      ignore_errors: yes

  vars:

    # Node-RED Server will wait for Video Server
    nodered_wait_for_videoserver: false

    # Max seconds Node-RED Server will wait
    nodered_wait_for_videoserver_timeout: 600
...
