---
- name: generate the Murmur config file
  template:
    src: mumble-server.ini.j2
    dest: /etc/mumble-server.ini
    owner: root
    group: mumble-server
    mode: 0660


- name: "Activate Murmur Chat service"
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: "{{ murmur_service_name }}"
    enabled: "{{ murmur_enabled }}"
    state: "{{ murmur_state }}"
  register: activate_murmur_service
  retries: 20
  until: activate_murmur_service is succeeded

- name: Generate random superuser password
  set_fact:
    murmur_superuser_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

- name: Write superuser password
  ansible.builtin.copy:
    content: "{{ murmur_superuser_password }}"
    dest: /etc/mumble-superuser
    owner: root
    group: root
    mode: 0660

- name: set superuser password
  command: murmurd -ini /etc/mumble-server.ini -supw "{{ murmur_superuser_password }}"
  failed_when: false

- name: restart murmur
  ansible.builtin.systemd_service:
    name: "{{ murmur_service_name }}"
    state: restarted
...
