---
dependencies:
  - role: nodejs
    vars:
      placeholder: "foo"

galaxy_info:
  role_name: murmur
  author: freetakteam
  description: Mumble VOIP
  license: license (EPL-2.0)
  min_ansible_version: '2.4'
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - freetakserver
    - tak
    - atak
    - mumble
    - murmur
    - voip
...
