---

- name: Make sure we have an 'fts' group
  ansible.builtin.group:
    name: fts
    state: present

- name: Allow 'fts' group to have passwordless sudo
  ansible.builtin.copy:
    content: "%fts ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/80-ansible-fts-user
    validate: 'visudo -cf %s'

- name: Add fts user to the fts group
  ansible.builtin.user:
    name: fts
    groups: fts,sudo
    group: fts
    append: yes
    state: present
    create_home: true
    generate_ssh_key: true
    ssh_key_file: .ssh/id_rsa
    system: true

- name: Join the current user to the fts group
  ansible.builtin.user:
    name: "{{ base_user.id }}"
    groups: fts
    state: present

#- name: Set up authorized keys for the installing user
#  ansible.posix.authorized_key:
#    user: fts
#    key: "{{ lookup('file', '/home/fts/.ssh/id_rsa.pub') }}"
#    state: present

- name: Establish fts base folder {{ fts_base_path }}
  ansible.builtin.file:
    path: "{{ fts_base_path }}"
    group: fts
    owner: fts
    recurse: true
    state: directory
    mode: u+rw,g+rw,o+r

- name: "deadsnakes python repository"
  block:
    - name: "deadsnakes python repo | add"
      ansible.builtin.deb822_repository:
        name: deadsnakes
        types: deb
        uris: "https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu"
        suites: "jammy"
        components: "main"
        signed_by: |-
          -----BEGIN PGP PUBLIC KEY BLOCK-----

          mQINBFl8fYEBEADQmGZ6pDrwY9iH9DVlwNwTOvOZ7q7lHXPl/TLfMs1tckMc/D9a
          hsdBN9VWtMmo+RySvhkIe8X15r65TFs2HE8ft6j2e/4K472pObM1hB+ajiU/wYX2
          Syq7DBlNm6YMP5/SyQzRxqis4Ja1uUjW4Q5/Csdf5In8uMzXj5D1P7qOiP2aNa0E
          r3w6PXWRTuTihWZOsHv8npyVYDBRR6gEZbd3r86snI/7o8Bfmad3KjbxL7aOdNMw
          AqQFaNKl7Y+UJpv1CNFIf+twcOoC0se1SrsVJlAH9HNHM7XGQsPUwpNvQlcmvr+t
          1vVS2m72lk3gyShDuJpi1TifGw+DoTqu54U0k+0sZm4pnQVeiizNkefU2UqOoGlt
          4oiG9nIhSX04xRlGes3Ya0OjNI5b1xbcYoR+r0c3odI+UCw3VSZtKDX/xlH1o/82
          b8ouXeE7LA1i4DvGNj4VSvoxv4ggIznxMf+PkWXWKwRGsbAAXF52rr4FUaeaKoIU
          DkJqHXAxrB3PQslZ+ZgBEukkQZF76NkqRqP1E7FXzZZMo2eEL7vtnhSzUlanOf42
          ECBoWHVoZQaRFMNbGpqlg9aWedHGyetMStS3nH1sqanr+i4I8VR/UH+ilarPTW3T
          E0apWlsH8+N3IKbRx2wgrRZNoQEuyVtvyewDFYShJB3Zxt7VCy67vKAl1QARAQAB
          tBxMYXVuY2hwYWQgUFBBIGZvciBkZWFkc25ha2VziQI4BBMBAgAiBQJZfH2BAhsD
          BgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRC6aTI2anVXdvwhD/4oI3yckeKn
          9aJNNTJsyw4ydMkIAOdG+jbZsYv/rN73UVQF1RA8HC71SDmbd0Nu80koBOX+USuL
          vvhoMIsARlD5dLx5f/zaQcYWJm/BtsMF/eZ4s1xsenwW6PpXd8FpaTn1qtg/8+O9
          99R4uSetAhhyf1vSRb/8U0sgSQd38mpZZFq352UuVisXnmCThj621loQubYJ3lwU
          LSLs8wmgo4XIYH7UgdavV9dfplPh0M19RHQL3wTyQP2KRNRq1rG7/n1XzUwDyqY6
          eMVhdVhvnxAGztvdFCySVzBRr/rCw6quhcYQwBqdqaXhz63np+4mlUNfd8Eu+Vas
          b/tbteF/pDu0yeFMpK4X09Cwn2kYYCpq4XujijW+iRWb4MO3G8LLi8oBAHP/k0CM
          /QvSRbbG8JDQkQDH37Efm8iE/EttJTixjKAIfyugmvEHfcrnxaMoBioa6h6McQrM
          vI8bJirxorJzOVF4kY7xXvMYwjzaDC8G0fTA8SzQRaShksR3USXZjz8vS6tZ+YNa
          mRHPoZ3Ua0bz4t2aCcu/fknVGsXcNBazNIK9WF2665Ut/b7lDbojXsUZ3PpuqOoe
          GQL9LRj7nmCI6ugoKkNp8ZXcGJ8BGw37Wep2ztyzDohXp6f/4mGgy2KYV9R4S8D5
          yBDUU6BS7Su5nhQMStfdfr4FffLmnvFC9w==
          =7hFk
          -----END PGP PUBLIC KEY BLOCK-----

    - name: "deadsnakes python repo | apt update cache"
      ansible.builtin.apt:
        update_cache: true
      register: update_deadsnakes_result

    - name: "deadsnakes python repo | apt upgrade"
      ansible.builtin.apt:
        upgrade: dist
      when: update_deadsnakes_result.changed

    - name: "deadsnakes python repo | apt autoremove"
      ansible.builtin.apt:
        autoremove: true
      when: update_deadsnakes_result.changed


#- name: "python repository | add"
#  ansible.builtin.apt_repository:
#    repo: "ppa:deadsnakes/nightly"

- name: "python repository | update apt repository"
  ansible.builtin.apt:
    update_cache: true

- name: Ensure the Python version {{ python3_version }} packages are installed
  ansible.builtin.package:
    name:
      - "python{{ python3_version }}"
      - "python{{ python3_version }}-venv"
      - "python{{ python3_version }}-dev"
      - "python3-virtualenv"
    state: present

- name: "Install pip packages"
  ansible.builtin.pip:
    name:
      - "pip"
      - "colorama==0.4.4"
      - "dnspython==2.2.1"
      - "eventlet==0.33.1"
      - "greenlet==2.0.2"
      - "uvicorn==0.29.0"
      - "jinja2==3.1.3"
      - "pyyaml==6.0.1"
      - "psutil==5.9.4"
    state: "present"
    virtualenv: "{{ fts_venv }}"
    virtualenv_python: "python{{ python3_version }}"

- name: "Set permissions for the {{ fts_venv }} virtual environment"
  ansible.builtin.file:
    path: "{{ fts_venv }}"
    group: fts
    owner: fts
    recurse: true
    state: directory
    mode: u+rw,g+rw,o+r

- name: "Establish the /var/run/fts directory for storing fts owned pid-files"
  block:
    - name: "define the fts-pid-dir"
      ansible.builtin.copy:
        src: fts-pid-dir.conf
        dest: "/etc/tmpfiles.d/fts-pid-dir.conf"
        owner: root
        group: root
        mode: 0664

    - name: "schedule the creation of the fts-pid-dir"
      ansible.builtin.copy:
        src: fts-pid-dir.service
        dest: "{{ unit_files_location }}/fts-pid-dir.service"
        owner: root
        group: root
        mode: 0664

    - name: Reload systemd to apply changes
      ansible.builtin.systemd_service:
        daemon_reload: yes

    - name: Ensure fts-pid-dir.service is started and enabled
      ansible.builtin.systemd_service:
        name: fts-pid-dir.service
        enabled: yes
        state: started
...
