---
- name: Update apt packages
  shell: sudo apt-get update
  register: apt_update
  retries: 5
  ignore_errors: true
  changed_when: false
  until: apt_update is success

- name: Upgrade apt packages
  shell: sudo apt-get upgrade -y
  register: apt_upgrade
  retries: 5
  ignore_errors: true
  changed_when: false
  until: apt_upgrade is success

- name: Detect systemctl file
  stat:
    path: /usr/local/bin/systemctl
  register: systemctl_file

- name: Create systemctl backup
  ansible.builtin.copy:
    src: /usr/local/bin/systemctl
    dest: /usr/local/bin/systemctl.backup
    remote_src: true
  when: systemctl_file.stat.exists

- name: Use systemctl workaround
  get_url:
    url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py
    dest: /usr/local/bin/systemctl
    mode: 0755
...
