---

- name: nodejs armored key of gpg key should use .asc extension
  block:
    - name: nodesource | apt key
      ansible.builtin.copy:
        src: nodesource-repo.gpg.asc
        dest: /etc/apt/keyrings/nodesource.gpg.asc

    - name: nodesource | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/nodesource.gpg.asc] https://deb.nodesource.com/node_20.x nodistro main"
        state: present

    - name: nodesource | apt update cache
      ansible.builtin.apt:
        update_cache: yes
      register: update_nodesource_result

    - name: nodesource | apt update
      ansible.builtin.apt:
        upgrade: dist
      when: update_nodesource_result.changed

    - name: nodesource | apt autoremove
      ansible.builtin.apt:
        autoremove: yes
      when: update_nodesource_result.changed

- name: Update apt packages
  shell: sudo apt-get update
  register: apt_update
  retries: 5
  ignore_errors: true
  changed_when: false
  until: apt_update is success

- name: Upgrade apt packages
  shell: sudo apt-get upgrade -y
  register: apt_upgrade
  retries: 5
  ignore_errors: true
  changed_when: false
  until: apt_upgrade is success

- name: Detect systemctl file
  stat:
    path: /usr/local/bin/systemctl
  register: systemctl_file

- name: Create systemctl backup
  ansible.builtin.copy:
    src: /usr/local/bin/systemctl
    dest: /usr/local/bin/systemctl.backup
    remote_src: true
  when: systemctl_file.stat.exists

- name: Use systemctl workaround
  get_url:
    url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py
    dest: /usr/local/bin/systemctl
    mode: 0755
...
