---

- name: Instantiate mumble-web config
  template:
    src: config.local.js.j2
    dest: "/var/www/mumble-web/config.local.js"
    owner: www-data
    group: www-data
    mode: 0664

- name: Template unit file
  become: true
  become_user: root
  template:
    src: mumble-web.service.j2
    dest: "{{ unit_files_location }}/{{ mumble_web_service_name }}.service"
    owner: root
    group: root
    mode: 0664

- name: Kill any currently running processes
  include_tasks: ../../common/tasks/kill.yml
  vars:
    process: "mumble-web"

- name: activate mumble service
  ansible.builtin.systemd_service:
    name: "{{ mumble_web_service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
  register: activate_mumble_web_state
  retries: 20
  until:
    - activate_mumble_web_state is succeeded
    - activate_mumble_web_state.status.ActiveState == "active"
...
